### ISSUE TITLE
Custom wrapper not showing up when etce-wrapper list is ran

### ISSUE THREAD

**Issue by roymatchuu** [adjacentlink/python-etce#10]
Hello, I am having some trouble integrating a custom wrapper into the ETCE framework. I followed the instructions detailed on this link: https://github.com/adjacentlink/python-etce/wiki/Extending-ETCE and have not had much success with it. 

Some notes to consider:
- There is an empty `__init.py__` in the wrapper directory alongside the wrapper itself
- I see the wrapper directory and the wrapper script and the `__init.py__` in the `/usr/lib/python*/site-packages/etcewrappers` folder.

**Comment by eschreiber-alink** [comment]
Some tips:

1. Place your wrapper file in a subdirectory in `/usr/lib/python*/site-packages/etcewrappers`, either one of the existing ones (utils, emane, etc.) or make one of your own so that you can manage it. You'll need the empty `__init__.py` file if you make your own subdirectory.
2. Start with a bare bones wrapper with the empty required methods, something like:

```
from etce.wrapper import Wrapper


class MyWrapper(Wrapper):
    """
   My Wrapper doc string
    """
    def register(self, registrar):
        pass

    def run(self, ctx):
        pass

    def stop(self, ctx):
        ctx.stop()
```

3. Once you place the wrapper, use `pydoc3` and/or `etce-wrapper list` to see that your python environment can find and load the wrapper without error.
4. Build up your methods from there borrowing from an existing wrapper and rechecking as with step 3.
 
Some things to consider here:
-  you should specify an input file the wrapper uses to trigger execution - [register it](https://github.com/adjacentlink/python-etce/blob/master/etcewrappers/emane/emane.py#L50) in `register` and [test for it](https://github.com/adjacentlink/python-etce/blob/master/etcewrappers/emane/emane.py#L85) in `run`.
- you'll typically want to daemonize the wrapped application so that it doesn't block execution. if the app has a native daemonize command line option, prefer that, but the etce ctx object has a [daemonize](https://github.com/adjacentlink/python-etce/blob/master/etce/wrappercontext.py#L187) call that will attempt to do it for you.
- if your wrapper seems generally useful, feed it back up in a pull request and we'll try to integrate it into the project.
